#name: Cleanup Old Runs

#on:
 # schedule:
    - cron: "0 0 * * *" # Runs daily at midnight UTC
  workflow_dispatch: # Allows manual trigger

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: Install GitHub CLI and jq
        run: |
          sudo apt-get update
          sudo apt-get install -y jq gh
          echo "${{ secrets.PAT_TOKEN }}" | gh auth login --with-token

      - name: Delete old workflow runs
        run: |
          KEEP=2
          WORKFLOW="Build, Push & Update Deployment to Argo CD"
          REPO="akylgit/python-jenkins-argocd-k8s"

          gh run list --repo "$REPO" --workflow "$WORKFLOW" --limit 100 --json databaseId | \
          jq -r ".[${KEEP}:] | .[].databaseId" | while read id; do
            echo "Deleting run ID: $id"
            echo "y" | gh run delete "$id" --repo "$REPO"
          done

