name: Build, Push & Update Deployment to Argo CD

on:
  push:
    branches:
      - main

jobs:
  build-push-update:
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: ${{ github.run_number }}

    steps:
      - name: Checkout application repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image using buildx
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: akyldocker25/cicd-e2e:${{ env.IMAGE_TAG }}

      - name: Checkout manifest repo
        uses: actions/checkout@v3
        with:
          repository: akylgit/python-jenkins-argocd-k8s
          token: ${{ secrets.GITHUB_TOKEN }}
          path: repo

      - name: Update deploy.yaml
        run: |
          cd repo/deploy
          sed -i "s|image: akyldocker25/cicd-e2e:.*|image: akyldocker25/cicd-e2e:${{ env.IMAGE_TAG }}|" deploy.yaml

      - name: Commit and push manifest update
        run: |
          cd repo/deploy
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add deploy.yaml
          git commit -m "Updated the deploy.yaml | GitHub Actions"
          git push origin main
